### ISSUE TITLE
"Shoot gun at rifle" does not work

### ISSUE THREAD

**Issue by zzxyz** [i7/counterfeit-monkey#48] opened 2016-07-09 00:34 UTC
"Shoot rifle with gun" is the required syntax.  Seems like the syntax above worked for other things although I don't have a save that can verify that.  

In any event, this parser issue caused me to finally resort to hints.

edit: I get that shoot is a weird verb, and that absent any other context, "shoot gun" doesn't tell you whether you're firing at the gun or with the gun.  Just one of those things where otherwise the parser is so good that I assumed I was barking up the entirely wrong tree and ended up stuck.  Great that I found the rump stabber because of that, though :)

**Comment by angstsmurf** [comment] 2016-07-09 11:27
Hmm, I can't seem to reproduce this, neither with the development version or the old 6G60 code.

"Shoot gun at rifle" seems to work as expected, and the parser seems to do a surprisingly good job with "shoot gun", "shoot rifle", "shoot gun with rifle", "shoot gun at rifle" and so on. Do you have any more details that could help here?

Mind you, this is with recompiled test builds and not the official release. If you or anyone else have save files for the official version anywhere near the final showdown with Atlantida, I'd be happy to try that out as well.

**Comment by angstsmurf** [comment] 2016-07-09 16:46
Seems to be fixed now in current git version. The parser really wasn't keen on shooting anything with the anagramming gun.

**Closed** 2016-07-09 16:47 UTC
Labels: bug
