### ISSUE TITLE
Goal about Waterstone and the T-inserter shows up too early

### ISSUE THREAD

**Issue by SabreCat** [i7/counterfeit-monkey#82] opened 2017-01-06 17:04 UTC
Trying another playthrough with the current repo, I've advanced to the point where I'm trying to chase down Brock. I visited the antiques shop and spoke with Kate about Brock. Where she pointed me was ambiguous (intentional, I'm sure), so I checked `goals`. At the top of my goals list was something to the effect of* "Convince Dr. Waterstone to show me the T-inserter". Now, I've replayed the early game several times and thus tend to skim over a lot of familiar text, but I don't recall anything about a Waterstone or a T-inserter coming up before this point. Is the goal displaying too early?

*Like a doofus, I played in the editor for a while, not realizing I couldn't restore saved games. So at the moment I can't confirm the exact language. XD

**Comment by angstsmurf** [comment] 2017-01-06 19:07
I'll have to investigate this further, but obviously the goal is showing too early. I've noticed something similar happening to me, but was not able find the cause or to reproduce it.

You should be able to restore saved games while running the game in the IDE unless you have recompiled since you made the save. Save files are not compatible across versions, I'm afraid.

**Comment by SabreCat** [comment] 2017-01-06 19:14
Huh--I haven't done anything to the code since playing yesterday, but I still get a nonspecific "restore failed" if I press Go, get through the intro questionnaire, and then try to restore. I'll play from a release later and see if it works any better for me, in any case.

**Comment by angstsmurf** [comment] 2017-01-06 23:30
Well, there is a good chance that pressing Go! actually compiles a new, save-incompatible game. 

That should only happen if "Always compile" is enabled in preferences or if the source has been changed, but I've seen it compile anyway. Otherwise, the status window will say "No compilation needed" and the game will start right away.

**Comment by curiousdannii** [comment] 2017-01-06 23:32
Inform includes today's date as the serial number, which would invalidate saves from yesterday.

**Comment by SabreCat** [comment] 2017-01-07 03:53
That'd explain it! I don't see any "Always compile" option, but it certainly acts like it's compiling every time. Simplest workaround would be to use a released .gblorb if I intend to play the same project over multiple days.

**Comment by SabreCat** [comment] 2017-01-07 04:50
Back on topic to the bug in question...

The Waterstone quest isn't the only thing showing up out of context. I checked `goals` right after obtaining the Origin Paste, while still hunting for Slango. My list looked like this:

> Speak to Professor Waterstone and get his invitation to see the T-inserter
> Find transport for getting past the traffic on High Street
> Meet your colleague Slango at Counterfeit Monkey
> Gain entrance to the Bureau
> Find Brock
> Talk to Lena at the Aquarium Bookstore

Of these, only "Meet your colleague" and "Talk to Lena" make any sense to me. "Find transport" was already done; the rest haven't come up yet.

**Comment by angstsmurf** [comment] 2017-01-07 05:16
Yes, it was a pretty weird bug. For some reason that I can't figure out, an activity that was supposed to only take place when examining the legend for the first time was carried out whenever the player REMEMBERed something. Now it should be fixed. Sorry about the unintended spoilers.

**Comment by SabreCat** [comment] 2017-01-07 16:10
Fixed in 2013326 and ad71751 yes?

**Comment by angstsmurf** [comment] 2017-01-07 20:40
Yes. I'm not sure why 2013326 is needed, if indeed it is. That goal is completed in another place (the explicitly enter car rule) which is not supposed to be possible to skip.

**Closed** 2017-01-07 22:16 UTC
