### ISSUE TITLE
'All' (from ball) problems - should the death undo making it? And it's hard to use gel on?

### ISSUE THREAD

**Issue by Feldherren** [i7/counterfeit-monkey#45] opened 2016-06-25 11:32 UTC
From a ball you can make an all, with the right tool. The immediate response to this is being killed and getting the option to undo the last move (similar to making a rig from a ring - you end up safely with a rig after undoing the death from making it).
Because making the all isn't undone, you end up with an all sitting apparently-safely in your inventory. Because 'all' also refers to all items present, it's difficult to refer to this all to use the gel on it. Or to drop just the all, because 'drop all' drops your entire inventory. 'get all' picks everything up.
How am I supposed to get my ball back?

**Comment by angstsmurf** [comment] 2016-06-25 11:38
That is exactly the kind of bug we tried to fix with release 6. Are you sure you are using the [latest version](http://www.intfiction.org/forum/viewtopic.php?f=19&t=20057)?

**Comment by Feldherren** [comment] 2016-06-25 12:04
Yeah, I was using version 5, as that's the one that's available on Emily Short's website. I can't continue my existing save on 6, it seems.

**Comment by angstsmurf** [comment] 2016-06-25 12:12
What interpreter are you using? If you send the save file, I'll see what I can do.

**Comment by Feldherren** [comment] 2016-06-25 12:18
Gargoyle.
[Counterfeit Monkey-5.zip](https://github.com/i7/counterfeit-monkey/files/333056/Counterfeit.Monkey-5.zip)

**Comment by angstsmurf** [comment] 2016-06-25 12:28
Right, but that is a save done before making the all, right? I was thinking that I might help you get the ball back so that you could finish your game with the old version.

If you are all right with continuing from that save, just make sure to answer NO to any "Shall we suppose we didn't?" after dying and then type undo instead, and you should be fine. If your interpreter supports undo in this game, that is.

**Comment by Feldherren** [comment] 2016-06-25 12:54
Yes, before making the all. I wasn't at that point when the save was made, so I just went back to an earlier save before I'd done that, and continued from there.

**Comment by angstsmurf** [comment] 2016-06-25 13:06
Yeah, that is a known problem with Gargoyle. Are you on Windows? I'm not an expert on Windows interpreters, but I think that there are other interpreters that support both undo in Counterfeit Monkey and the Gargoyle save game format.

**Comment by Feldherren** [comment] 2016-06-25 13:28
I am on windows, but this issue aside I'm very fond of Gargoyle for playing most games by itself.

**Comment by angstsmurf** [comment] 2016-06-25 13:32
Yeah, it seems to be the best Windows interpreter for most games. Older versions of Counterfeit Monkey is the exception, I'm afraid.

**Comment by curiousdannii** [comment] 2016-06-25 23:52
If you switch to using glulxe in Gargoyle, then undo will work. It's just the git VM that doesn't have enough space to undo.

**Comment by curiousdannii** [comment] 2016-06-25 23:54
Closed as duplicate of #3 (but keep chatting here if you can't get glulxe in Gargoyle working.)

**Closed by curiousdannii** 2016-06-25 23:54 UTC
Labels: duplicate
