### ISSUE TITLE
Runtime problem P10 when trying to remove letters from the current room

### ISSUE THREAD

**Issue by eriktorbjorn** [i7/counterfeit-monkey#209] opened 2023-04-20 18:04 UTC
I figured I needed a friend, so in the first room I tried this:

```
>POINT E-REMOVER AT HERE
*** Run-time problem P10: Since Back Alley is 
not allowed the property “seen”, it is against the 
rules to try to use it.


The E-remover is powerless to make Back Alley 
into anything called “back ally”, but perhaps this 
is to be expected considering the size of the 
target. The device is after all a mere portable 
device with limited resources.

If we were to succeed in transforming the entire 
room — mercifully, that’s unlikely, given the 
power requirements — but if we did succeed, 
you and I would be rendered inanimate, along 
with any other hapless passers-by.
```

I can reproduce this in release 9, 10 and 11. Not in release 5, 6, 7, or 8. It also only happens if I try to remove a letter that's in the room's name. Otherwise, I only get the second paragraph.

**Comment by angstsmurf** [comment] 2023-04-20 20:06
Thanks for reporting this! It was caused by 94fbeac and is fixed by df99b2d.

**Closed** 2023-04-20 20:05 UTC
